-- Multi-tenant companies table. Idempotent — safe to run multiple times.
-- Run once in Supabase SQL editor.

create table if not exists public.companies (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now()
);

-- Seed default tenant (id=1) used as the fallback for existing rows and
-- single-tenant deployments. Idempotent — won't duplicate or overwrite.
insert into public.companies (id, name)
values (1, 'Default Company')
on conflict (id) do nothing;

comment on table public.companies is
  'Multi-tenant root. customers/conversations/line_users.company_id reference this table.';
