-- CRM in-app notification center. Run once in Supabase SQL editor.

create table if not exists public.crm_notifications (
  id bigint generated by default as identity primary key,
  company_id integer not null default 1,
  customer_id text,
  type text not null,
  title text not null,
  body text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists crm_notifications_company_created_idx
  on public.crm_notifications (company_id, created_at desc);

create index if not exists crm_notifications_company_unread_idx
  on public.crm_notifications (company_id, read_at)
  where read_at is null;

comment on table public.crm_notifications is
  'In-app CRM notifications: LINE messages, new customers, bindings, reminders, urgent.';
