-- LINE conversation log for CRM customers.
-- Run once in Supabase SQL editor.

create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  line_user_id text not null,
  customer_id text,
  message_text text not null,
  direction text not null default 'inbound',
  created_at timestamptz not null default now()
);

create index if not exists conversations_line_user_id_idx
  on public.conversations (line_user_id);

create index if not exists conversations_customer_id_idx
  on public.conversations (customer_id);

create index if not exists conversations_created_at_idx
  on public.conversations (created_at desc);

comment on column public.conversations.direction is
  '"inbound" (customer → bot) or "outbound" (bot → customer).';
comment on column public.conversations.customer_id is
  'Bound customers.id (stringified). NULL when sender is not yet bound via 綁定.';
