-- LINE webhook user bindings.
-- Run once in Supabase SQL editor before enabling the webhook.

create table if not exists public.line_users (
  id bigint generated by default as identity primary key,
  line_user_id text not null unique,
  display_name text,
  created_at timestamptz not null default now()
);

create index if not exists line_users_line_user_id_idx
  on public.line_users (line_user_id);
