-- Default workspace per company (SaaS tenant sub-scope).
-- Safe to re-run.

create table if not exists public.workspaces (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies (id) on delete cascade,
  name text not null,
  owner_user_id uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists workspaces_company_id_idx
  on public.workspaces (company_id);

comment on table public.workspaces is
  'Per-company workspace; AI/CRM flows resolve company_id via workspace id.';
