-- Company AI plan, monthly usage counters, and usage audit log.
-- Safe to re-run (IF NOT EXISTS / idempotent alters).

alter table public.companies
  add column if not exists plan_status text not null default 'trial';

alter table public.companies
  add column if not exists trial_started_at timestamptz;

alter table public.companies
  add column if not exists trial_ends_at timestamptz;

alter table public.companies
  add column if not exists ai_monthly_limit int not null default 90;

alter table public.companies
  add column if not exists ai_used_this_month int not null default 0;

alter table public.companies
  add column if not exists ai_usage_month text;

comment on column public.companies.plan_status is 'trial | paid | expired';
comment on column public.companies.ai_usage_month is 'YYYY-MM calendar month for ai_used_this_month counter';

create table if not exists public.ai_usage_logs (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies (id) on delete cascade,
  user_id uuid references auth.users (id) on delete set null,
  feature text not null,
  estimated_tokens int,
  created_at timestamptz not null default now()
);

create index if not exists ai_usage_logs_company_created_idx
  on public.ai_usage_logs (company_id, created_at desc);

create index if not exists ai_usage_logs_company_month_idx
  on public.ai_usage_logs (company_id, created_at);

comment on table public.ai_usage_logs is 'Per-action AI usage audit for billing and limits';

-- Backfill existing companies: 30-day trial from created_at, 90 actions/month.
update public.companies
set
  plan_status = coalesce(nullif(trim(plan_status), ''), 'trial'),
  trial_started_at = coalesce(trial_started_at, created_at, now()),
  trial_ends_at = coalesce(
    trial_ends_at,
    coalesce(created_at, now()) + interval '30 days'
  ),
  ai_monthly_limit = case
    when coalesce(plan_status, 'trial') = 'paid' then greatest(coalesce(ai_monthly_limit, 0), 1000)
    else coalesce(nullif(ai_monthly_limit, 0), 90)
  end,
  ai_used_this_month = coalesce(ai_used_this_month, 0),
  ai_usage_month = coalesce(ai_usage_month, to_char(now() at time zone 'UTC', 'YYYY-MM'))
where trial_started_at is null
   or trial_ends_at is null
   or ai_usage_month is null
   or plan_status is null;

alter table public.ai_usage_logs enable row level security;

do $$
declare pol record;
begin
  for pol in
    select policyname from pg_policies
    where schemaname = 'public' and tablename = 'ai_usage_logs'
  loop
    execute format('drop policy if exists %I on public.ai_usage_logs', pol.policyname);
  end loop;
end $$;

create policy ai_usage_logs_select_member
  on public.ai_usage_logs
  for select
  to authenticated
  using (public.is_member_of_company(company_id));

grant select on public.ai_usage_logs to authenticated;
