-- =============================================================================
-- Tenant auth: company_members + strict RLS (authenticated users only)
-- =============================================================================
-- Run once in Supabase SQL Editor after add_companies.sql + add_company_id_columns.sql
-- Safe to re-run (idempotent policy drops).

-- 1. Link Supabase Auth users to companies
create table if not exists public.company_members (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null default 'owner',
  created_at timestamptz not null default now(),
  unique (company_id, user_id)
);

create index if not exists company_members_user_id_idx
  on public.company_members (user_id);

create index if not exists company_members_company_id_idx
  on public.company_members (company_id);

comment on table public.company_members is
  'Maps auth.users to companies. RLS on CRM tables uses this membership.';

alter table public.companies
  add column if not exists owner_user_id uuid references auth.users (id) on delete set null;

alter table public.customers
  add column if not exists created_by_user_id uuid references auth.users (id) on delete set null;

-- 2. Helper: company ids the current user may access
create or replace function public.user_company_ids()
returns setof bigint
language sql
stable
security definer
set search_path = public
as $$
  select company_id
  from public.company_members
  where user_id = auth.uid();
$$;

revoke all on function public.user_company_ids() from public;
grant execute on function public.user_company_ids() to authenticated;

create or replace function public.is_member_of_company(target_company_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.company_members
    where user_id = auth.uid()
      and company_id = target_company_id
  );
$$;

revoke all on function public.is_member_of_company(bigint) from public;
grant execute on function public.is_member_of_company(bigint) to authenticated;

-- 3. company_members RLS
alter table public.company_members enable row level security;

do $$
declare pol record;
begin
  for pol in
    select policyname from pg_policies
    where schemaname = 'public' and tablename = 'company_members'
  loop
    execute format('drop policy if exists %I on public.company_members', pol.policyname);
  end loop;
end $$;

grant select, insert on public.company_members to authenticated;

create policy "company_members_select_own"
  on public.company_members for select to authenticated
  using (user_id = auth.uid());

create policy "company_members_insert_own"
  on public.company_members for insert to authenticated
  with check (user_id = auth.uid());

-- 4. companies RLS
alter table public.companies enable row level security;

do $$
declare pol record;
begin
  for pol in
    select policyname from pg_policies
    where schemaname = 'public' and tablename = 'companies'
  loop
    execute format('drop policy if exists %I on public.companies', pol.policyname);
  end loop;
end $$;

grant select, insert, update on public.companies to authenticated;

create policy "companies_select_member"
  on public.companies for select to authenticated
  using (
    owner_user_id = auth.uid()
    or id in (select public.user_company_ids())
  );

create policy "companies_insert_authenticated"
  on public.companies for insert to authenticated
  with check (
    owner_user_id = auth.uid()
    or owner_user_id is null
  );

create policy "companies_update_owner"
  on public.companies for update to authenticated
  using (
    owner_user_id = auth.uid()
    or id in (select public.user_company_ids())
  )
  with check (id in (select public.user_company_ids()));

-- 5. customers RLS
alter table public.customers enable row level security;

do $$
declare pol record;
begin
  for pol in
    select policyname from pg_policies
    where schemaname = 'public' and tablename = 'customers'
  loop
    execute format('drop policy if exists %I on public.customers', pol.policyname);
  end loop;
end $$;

grant select, insert, update, delete on public.customers to authenticated;

create policy "customers_select_member"
  on public.customers for select to authenticated
  using (company_id in (select public.user_company_ids()));

create policy "customers_insert_member"
  on public.customers for insert to authenticated
  with check (
    company_id in (select public.user_company_ids())
    and (created_by_user_id is null or created_by_user_id = auth.uid())
  );

create policy "customers_update_member"
  on public.customers for update to authenticated
  using (company_id in (select public.user_company_ids()))
  with check (company_id in (select public.user_company_ids()));

create policy "customers_delete_member"
  on public.customers for delete to authenticated
  using (company_id in (select public.user_company_ids()));

-- 6. conversations RLS (replace permissive anon policies)
alter table public.conversations enable row level security;

do $$
declare pol record;
begin
  for pol in
    select policyname from pg_policies
    where schemaname = 'public' and tablename = 'conversations'
  loop
    execute format('drop policy if exists %I on public.conversations', pol.policyname);
  end loop;
end $$;

grant select, insert, delete on public.conversations to authenticated;

create policy "conversations_select_member"
  on public.conversations for select to authenticated
  using (company_id in (select public.user_company_ids()));

create policy "conversations_insert_member"
  on public.conversations for insert to authenticated
  with check (company_id in (select public.user_company_ids()));

create policy "conversations_delete_member"
  on public.conversations for delete to authenticated
  using (company_id in (select public.user_company_ids()));

-- 7. line_users RLS
alter table public.line_users enable row level security;

do $$
declare pol record;
begin
  for pol in
    select policyname from pg_policies
    where schemaname = 'public' and tablename = 'line_users'
  loop
    execute format('drop policy if exists %I on public.line_users', pol.policyname);
  end loop;
end $$;

grant select, insert, update, delete on public.line_users to authenticated;

create policy "line_users_select_member"
  on public.line_users for select to authenticated
  using (company_id in (select public.user_company_ids()));

create policy "line_users_insert_member"
  on public.line_users for insert to authenticated
  with check (company_id in (select public.user_company_ids()));

create policy "line_users_update_member"
  on public.line_users for update to authenticated
  using (company_id in (select public.user_company_ids()))
  with check (company_id in (select public.user_company_ids()));

create policy "line_users_delete_member"
  on public.line_users for delete to authenticated
  using (company_id in (select public.user_company_ids()));

-- 8. crm_notifications RLS
alter table public.crm_notifications enable row level security;

do $$
declare pol record;
begin
  for pol in
    select policyname from pg_policies
    where schemaname = 'public' and tablename = 'crm_notifications'
  loop
    execute format('drop policy if exists %I on public.crm_notifications', pol.policyname);
  end loop;
end $$;

grant select, insert, update on public.crm_notifications to authenticated;

create policy "crm_notifications_select_member"
  on public.crm_notifications for select to authenticated
  using (company_id in (select public.user_company_ids()));

create policy "crm_notifications_insert_member"
  on public.crm_notifications for insert to authenticated
  with check (company_id in (select public.user_company_ids()));

create policy "crm_notifications_update_member"
  on public.crm_notifications for update to authenticated
  using (company_id in (select public.user_company_ids()))
  with check (company_id in (select public.user_company_ids()));

-- 9. Per-company settings (LINE reminder etc.)
create table if not exists public.company_settings (
  company_id bigint not null references public.companies (id) on delete cascade,
  key text not null,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (company_id, key)
);

comment on table public.company_settings is
  'Tenant-scoped settings (e.g. line_reminder). Replaces global app_settings for CRM users.';

alter table public.company_settings enable row level security;

do $$
declare pol record;
begin
  for pol in
    select policyname from pg_policies
    where schemaname = 'public' and tablename = 'company_settings'
  loop
    execute format('drop policy if exists %I on public.company_settings', pol.policyname);
  end loop;
end $$;

grant select, insert, update on public.company_settings to authenticated;

create policy "company_settings_select_member"
  on public.company_settings for select to authenticated
  using (company_id in (select public.user_company_ids()));

create policy "company_settings_insert_member"
  on public.company_settings for insert to authenticated
  with check (company_id in (select public.user_company_ids()));

create policy "company_settings_update_member"
  on public.company_settings for update to authenticated
  using (company_id in (select public.user_company_ids()))
  with check (company_id in (select public.user_company_ids()));

-- Revoke broad anon access on tenant tables (authenticated + RLS only)
revoke all on table public.customers from anon;
revoke all on table public.conversations from anon;
revoke all on table public.line_users from anon;
revoke all on table public.crm_notifications from anon;
revoke all on table public.companies from anon;
revoke all on table public.company_members from anon;
revoke all on table public.company_settings from anon;
